### PR TITLE
Filter branch

### PR DESCRIPTION
**Pull request by eclipse162**
- adds color to each post
- adds filter functionality to main feed and profile history
- adds profile total posts count 
- adds create new post button in profile

Known Issues:
- removeButton was changed back to toggleButton since removeButton ID could not be found
- the same case was made for search_button in SearchActivity, assuming that the correct IDs will be added in a later pull request

### CODE REVIEW

**Comment by raimoe** [comment]
When selecting filters on profile activity app crashes

**Comment by raimoe** [comment]
Dunno how to request Kyle to review

**Comment by eclipse162** [comment]
Fixed profile filters crashing on select

**Comment by raimoe** [comment]
I'm not sure if this is intentional or not but when going from main feed to profile activity - Filters remain on and ;   when going from profile activity back to main feed filters automatically turn off. I think it is fine this way but just mentioning.

**Comment by raimoe** [comment]
Also option in followers/following tabs is OFF in this branch and REMOVE in masterPrototype, is functionality the same just different wording?

**Comment by eclipse162** [comment]
Fixed the button wording, should have the same functionality but the default text is REMOVE

**Pull request closed without merging**
